API_COMPONENTS_SHOW_ENDPOINT = '/api/components/show'

API_PROJECTS_BULK_DELETE_ENDPOINT = '/api/projects/bulk_delete'
API_PROJECTS_SEARCH_ENDPOINT = '/api/projects/search'
API_PROJECTS_CREATE_ENDPOINT = '/api/projects/create'
API_PROJECTS_DELETE_ENDPOINT = '/api/projects/delete'
API_PROJECTS_UPDATE_VISIBILITY_ENDPOINT = '/api/projects/update_visibility'
API_PROJECTS_UPDATE_KEY_ENDPOINT = '/api/projects/update_key'

API_USERS_SEARCH_ENDPOINT = '/api/users/search'
API_USERS_CREATE_ENDPOINT = '/api/users/create'
API_USERS_UPDATE_ENDPOINT = '/api/users/update'
API_USERS_CHANGE_PASSWORD_ENDPOINT = '/api/users/change_password'
API_USERS_GROUPS_ENDPOINT = '/api/users/groups'
API_USERS_DEACTIVATE_ENDPOINT = '/api/users/deactivate'
API_USERS_UPDATE_LOGIN_ENDPOINT = '/api/users/update_login'

API_USER_GROUPS_SEARCH_ENDPOINT = '/api/user_groups/search'
API_USER_GROUPS_CREATE_ENDPOINT = '/api/user_groups/create'
API_USER_GROUPS_DELETE_ENDPOINT = '/api/user_groups/delete'
API_USER_GROUPS_UPDATE_ENDPOINT = '/api/user_groups/update'
API_USER_GROUPS_USERS_ENDPOINT = '/api/user_groups/users'
API_USER_GROUPS_ADD_USER_ENDPOINT = '/api/user_groups/add_user'
API_USER_GROUPS_REMOVE_USER_ENDPOINT = '/api/user_groups/remove_user'

API_PERMISSIONS_ADD_GROUP_ENDPOINT = '/api/permissions/add_group'
API_PERMISSIONS_REMOVE_GROUP_ENDPOINT = '/api/permissions/remove_group'
API_PERMISSIONS_ADD_USER_ENDPOINT = '/api/permissions/add_user'
API_PERMISSIONS_REMOVE_USER_ENDPOINT = '/api/permissions/remove_user'
API_PERMISSIONS_APPLY_TEMPLATE_ENDPOINT = '/api/permissions/apply_template'
API_PERMISSIONS_ADD_GROUP_TO_TEMPLATE_ENDPOINT = '/api/permissions/add_group_to_template'
API_PERMISSIONS_ADD_PROJECT_CREATOR_TO_TEMPLATE_ENDPOINT = '/api/permissions/add_project_creator_to_template'
API_PERMISSIONS_ADD_USER_TO_TEMPLATE_ENDPOINT = '/api/permissions/add_user_to_template'
API_PERMISSIONS_BULK_APPLY_TEMPLATE_ENDPOINT = '/api/permissions/bulk_apply_template'
API_PERMISSIONS_CREATE_TEMPLATE_ENDPOINT = '/api/permissions/create_template'
API_PERMISSIONS_DELETE_TEMPLATE_ENDPOINT = '/api/permissions/delete_template'
API_PERMISSIONS_REMOVE_GROUP_FROM_TEMPLATE_ENDPOINT = '/api/permissions/remove_group_from_template'
API_PERMISSIONS_REMOVE_PROJECT_CREATOR_FROM_TEMPLATE_ENDPOINT = '/api/permissions/remove_project_creator_from_template'
API_PERMISSIONS_REMOVE_USER_FROM_TEMPLATE_ENDPOINT = '/api/permissions/remove_user_from_template'
API_PERMISSIONS_SEARCH_TEMPLATES_ENDPOINT = '/api/permissions/search_templates'
API_PERMISSIONS_SET_DEFAULT_TEMPLATE_ENDPOINT = '/api/permissions/set_default_template'
API_PERMISSIONS_UPDATE_TEMPLATE_ENDPOINT = '/api/permissions/update_template'

API_CE_ACTIVITY_ENDPOINT = '/api/ce/activity'
API_CE_ACTIVITY_STATUS_ENDPOINT = '/api/ce/activity_status'
API_CE_COMPONENT_ENDPOINT = '/api/ce/component'
API_CE_TASK_ENDPOINT = '/api/ce/task'

API_MEASURES_COMPONENT_ENDPOINT = '/api/measures/component'
API_MEASURES_COMPONENT_TREE_ENDPOINT = '/api/measures/component_tree'
API_MEASURES_SEARCH_HISTORY_ENDPOINT = '/api/measures/search_history'

API_PROJECT_BRANCHES_LIST_ENDPOINT = '/api/project_branches/list'
API_PROJECT_BRANCHES_RENAME_ENDPOINT = '/api/project_branches/rename'
API_PROJECT_BRANCHES_DELETE_ENDPOINT = '/api/project_branches/delete'

API_NOTIFICATIONS_ADD_ENDPOINT = '/api/notifications/add'
API_NOTIFICATIONS_LIST_ENDPOINT = '/api/notifications/list'
API_NOTIFICATIONS_REMOVE_ENDPOINT = '/api/notifications/remove'

API_ISSUES_SEARCH_ENDPOINT = '/api/issues/search'
API_ISSUES_ASSIGN_ENDPOINT = '/api/issues/assign'
API_ISSUES_DO_TRANSITION_ENDPOINT = '/api/issues/do_transition'
API_ISSUES_ADD_COMMENT_ENDPOINT = '/api/issues/add_comment'
API_ISSUES_EDIT_COMMENT_ENDPOINT = '/api/issues/edit_comment'
API_ISSUES_DELETE_COMMENT_ENDPOINT = '/api/issues/delete_comment'
API_ISSUES_SET_SEVERITY_ENDPOINT = '/api/issues/set_severity'
API_ISSUES_SET_TYPE_ENDPOINT = '/api/issues/set_type'
API_ISSUES_AUTHORS_ENDPOINT = '/api/issues/authors'
API_ISSUES_BULK_CHANGE_ENDPOINT = '/api/issues/bulk_change'
API_ISSUES_CHANGELOG_ENDPOINT = '/api/issues/changelog'
API_ISSUES_SET_TAGS_ENDPOINT = '/api/issues/set_tags'
API_ISSUES_TAGS_ENDPOINT = '/api/issues/tags'

API_PROJECT_LINKS_CREATE_ENDPOINT = '/api/project_links/create'
API_PROJECT_LINKS_DELETE_ENDPOINT = '/api/project_links/delete'
API_PROJECT_LINKS_SEARCH_ENDPOINT = '/api/project_links/search'

API_QUALITYGATES_PROJECT_STATUS_ENDPOINT = '/api/qualitygates/project_status'
API_QUALITYGATES_LIST_ENDPOINT = '/api/qualitygates/list'
API_QUALITYGATES_SELECT_ENDPOINT = '/api/qualitygates/select'
API_QUALITYGATES_DESELECT_ENDPOINT = '/api/qualitygates/deselect'
API_QUALITYGATES_SHOW_ENDPOINT = '/api/qualitygates/show'
API_QUALITYGATES_GET_BY_PROJECT_ENDPOINT = '/api/qualitygates/get_by_project'
API_QUALITYGATES_COPY_ENDPOINT = '/api/qualitygates/copy'
API_QUALITYGATES_CREATE_ENDPOINT = '/api/qualitygates/create'
API_QUALITYGATES_CREATE_CONDITION_ENDPOINT = '/api/qualitygates/create_condition'
API_QUALITYGATES_DELETE_CONDITION_ENDPOINT = '/api/qualitygates/delete_condition'
API_QUALITYGATES_DESTROY_ENDPOINT = '/api/qualitygates/destroy'
API_QUALITYGATES_RENAME_ENDPOINT = '/api/qualitygates/rename'
API_QUALITYGATES_SEARCH_ENDPOINT = '/api/qualitygates/search'
API_QUALITYGATES_SET_AS_DEFAULT_ENDPOINT = '/api/qualitygates/set_as_default'
API_QUALITYGATES_UPDATE_CONDITION_ENDPOINT = '/api/qualitygates/update_condition'

API_COMPONTENTS_SHOW_ENDPOINT = '/api/components/show'
API_COMPONTENTS_SEARCH_ENDPOINT = '/api/components/search'
API_COMPONTENTS_TREE_ENDPOINT = '/api/components/tree'

API_RULES_SEARCH_ENDPOINT = '/api/rules/search'
API_RULES_CREATE_ENDPOINT = '/api/rules/create'
API_RULES_UPDATE_ENDPOINT = '/api/rules/update'
API_RULES_DELETE_ENDPOINT = '/api/rules/delete'
API_RULES_SHOW_ENDPOINT = '/api/rules/show'
API_RULES_TAGS_ENDPOINT = '/api/rules/tags'
API_RULES_REPOSITORIES_ENDPOINT = '/api/rules/repositories'

API_QUALITYPROFILES_ACTIVATE_RULE_ENDPOINT = '/api/qualityprofiles/activate_rule'
API_QUALITYPROFILES_SEARCH_ENDPOINT = '/api/qualityprofiles/search'
API_QUALITYPROFILES_DELETE_ENDPOINT = '/api/qualityprofiles/delete'
API_QUALITYPROFILES_SET_DEFAULT_ENDPOINT = '/api/qualityprofiles/set_default'
API_QUALITYPROFILES_ADD_PROJECT_ENDPOINT = '/api/qualityprofiles/add_project'
API_QUALITYPROFILES_REMOVE_PROJECT_ENDPOINT = '/api/qualityprofiles/remove_project'
API_QUALITYPROFILES_ACTIVATE_RULES_ENDPOINT = '/api/qualityprofiles/activate_rules'
API_QUALITYPROFILES_BACKUP_ENDPOINT = '/api/qualityprofiles/backup'
API_QUALITYPROFILES_CHANGE_PARENT_ENDPOINT = '/api/qualityprofiles/change_parent'
API_QUALITYPROFILES_CHANGELOG_ENDPOINT = '/api/qualityprofiles/changelog'
API_QUALITYPROFILES_COPY_ENDPOINT = '/api/qualityprofiles/copy'
API_QUALITYPROFILES_CREATE_ENDPOINT = '/api/qualityprofiles/create'
API_QUALITYPROFILES_DEACTIVATE_RULE_ENDPOINT = '/api/qualityprofiles/deactivate_rule'
API_QUALITYPROFILES_DEACTIVATE_RULES_ENDPOINT = '/api/qualityprofiles/deactivate_rules'
API_QUALITYPROFILES_EXPORT_ENDPOINT = '/api/qualityprofiles/export'
API_QUALITYPROFILES_EXPORTERS_ENDPOINT = '/api/qualityprofiles/exporters'
API_QUALITYPROFILES_IMPORTERS_ENDPOINT = '/api/qualityprofiles/importers'
API_QUALITYPROFILES_INHERITANCE_ENDPOINT = '/api/qualityprofiles/inheritance'
API_QUALITYPROFILES_PROJECTS_ENDPOINT = '/api/qualityprofiles/projects'
API_QUALITYPROFILES_RENAME_ENDPOINT = '/api/qualityprofiles/rename'
API_QUALITYPROFILES_RESTORE_ENDPOINT = '/api/qualityprofiles/restore'

API_DUPLICATIONS_SHOW_ENDPOINT = '/api/duplications/show'

API_PDFREPORT_GET_ENDPOINT = '/api/pdfreport/get'

API_METRICS_SEARCH_ENDPOINT = '/api/metrics/search'
API_METRICS_TYPES_ENDPOINT = '/api/metrics/types'

API_SETTINGS_LIST_DEFINITIONS_ENDPOINT = '/api/settings/list_definitions'
API_SETTINGS_RESET_ENDPOINT = '/api/settings/reset'
API_SETTINGS_SET_ENDPOINT = '/api/settings/set'
API_SETTINGS_VALUES_ENDPOINT = '/api/settings/values'

API_SOURCES_SCM_ENDPOINT = '/api/sources/scm'
API_SOURCES_SHOW_ENDPOINT = '/api/sources/show'
API_SOURCES_RAW_ENDPOINT = '/api/sources/raw'

API_AUTH_LOGIN_ENDPOINT = '/api/authentication/login'
API_AUTH_LOGOUT_ENDPOINT = '/api/authentication/logout'
API_AUTH_VALIDATE_ENDPOINT = '/api/authentication/validate'

API_FAVORITES_ADD_ENDPOINT = '/api/favorites/add'
API_FAVORITES_REMOVE_ENDPOINT = '/api/favorites/remove'
API_FAVORITES_SEARCH_ENDPOINT = '/api/favorites/search'

API_LANGUAGES_LIST_ENDPOINT = '/api/languages/list'

API_PROJECT_BADGES_MEASURE_ENDPOINT = '/api/project_badges/measure'
API_PROJECT_BADGES_QUALITY_GATE_ENDPOINT = '/api/project_badges/quality_gate'

API_PROJECT_TAGS_SEARCH_ENDPOINT = '/api/project_tags/search'
API_PROJECT_TAGS_SET_ENDPOINT = '/api/project_tags/set'

API_PROJECT_PULL_REQUESTS_DELETE_ENDPOINT = '/api/project_pull_requests/delete'
API_PROJECT_PULL_REQUESTS_LIST_ENDPOINT = '/api/project_pull_requests/list'

API_PROJECT_ANALYSES_CREATE_EVENT_ENDPOINT = '/api/project_analyses/create_event'
API_PROJECT_ANALYSES_DELETE_ENDPOINT = '/api/project_analyses/delete'
API_PROJECT_ANALYSES_DELETE_EVENT_ENDPOINT = '/api/project_analyses/delete_event'
API_PROJECT_ANALYSES_SEARCH_ENDPOINT = '/api/project_analyses/search'
API_PROJECT_ANALYSES_SET_BASELINE_ENDPOINT = '/api/project_analyses/set_baseline'
API_PROJECT_ANALYSES_UNSET_BASELINE_ENDPOINT = '/api/project_analyses/unset_baseline'
API_PROJECT_ANALYSES_UPDATE_EVENT_ENDPOINT = '/api/project_analyses/update_event'

API_SERVER_VERSION_ENDPOINT = '/api/server/version'
